config/routes.rb
Site::Application.routes.draw do

    get 'auth/:provider/callback', to: 'sessions#create'
    get 'auth/failure', to: redirect('/')
    get 'signout', to: 'sessions#destroy', as: 'signout'

    root to: 'home#home_page'

    get 'about_romania', to: 'about_romania#about_page'
    get 'destinations', to: 'destinations#destinations_page'
    get 'multimedia', to: 'multimedia#multimedia_page'
    get 'special_interest', to: 'special_interest#special_interest_page'
    get 'trip_planner', to: 'trip_planner#trip_planner_page'
    get 'what_to_do', to: 'what_to_do#what_to_do_page'
    
    match '/destinations/top' => 'destinations#top', :as => 'top', :via => :get

    match '/destinations/comment/:clas/:loc' => 'destinations#comment', :as => 'comments', :via => :get
    match '/destinations/comment/:clas/:loc' => 'destinations#create', :via => :post

    match '/destinations/rate_loc/:location_id/:note' => 'destinations#rate_loc', :via => :post
     match '/destinations/rate_loc/:location_id' => 'destinations#rate_loc_value', :via => :get
    match '/destinations/cities' => 'destinations#cities', :as => 'cities', :via => :get
    match '/destinations/castles' => 'destinations#castles', :as => 'castles', :via => :get
    match '/destinations/regions' => 'destinations#regions', :as => 'regions', :via => :get
    match '/destinations' => 'destinations#topdestination', :as => 'topdestination', :via => :get

    match '/special_interest/architecture' => 'special_interest#architecture', :as => 'architecture', :via => :get
  
    match '/special_interest/festivals_events' => 'special_interest#festivals_events', :as => 'festivals_events', :via => :get
    match '/special_interest/food_wine' => 'special_interest#food_wine', :as => 'food_wine', :via => :get
    match '/special_interest/traditions_folklore' => 'special_interest#traditions_folklore', :as => 'traditions_folklore', :via => :get
    match '/special_interest/rate_event/:event_id/:note' => 'special_interest#rate_event',  :via => :post
     match '/special_interest/rate_event/:event_id' => 'special_interest#rate_event_value', :via => :get

    
    match '/trip_planner/entry_requirements' => 'trip_planner#entry_requirements', :as => 'entry_requirements', :via => :get
    match '/trip_planner/itinerary_ideas' => 'trip_planner#itinerary_ideas', :as => 'itinerary_ideas', :via => :get
    match '/trip_planner/practical_information' => 'trip_planner#practical_information', :as => 'practical_information', :via => :get
    match '/trip_planner/transportation' => 'trip_planner#transportation', :as => 'transportation', :via => :get

  

end

app/models/castle.rb
class Castle < ActiveRecord::Base 
	belongs_to :location
end

app/models/city.rb
class City < ActiveRecord::Base
	belongs_to :location
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	has_many :users
	has_many :locations
	validates :com_text, presence: true
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :rate_event
	has_one :location
end

app/models/event_address.rb
class EventAddress < ActiveRecord::Base
	belongs_to :location
end

app/models/event_comment.rb
class EventComment < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
	has_many :top_destinations
	has_many :cities
	has_many :castles
	has_many :regions
	has_many :event_addresses
	belongs_to :rate_location
	belongs_to :comment
	belongs_to :event
end

app/models/rate_event.rb
class RateEvent < ActiveRecord::Base
	has_many :users
	has_many :events
end

app/models/rate_location.rb
class RateLocation < ActiveRecord::Base
	has_many :locations
	has_many :users
end

app/models/region.rb
class Region < ActiveRecord::Base
	belongs_to :location
end

app/models/top_destination.rb
class TopDestination < ActiveRecord::Base
	belongs_to :location
end

app/models/user.rb
class User < ActiveRecord::Base
	def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
  belongs_to :rate_location
  belongs_to :rate_event
  belongs_to :comment
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def home_page
			events = Event.all.order("date ASC")
			@monday = {} 
			@monday.compare_by_identity
			@tuesday = {}
			@tuesday.compare_by_identity
			@wednesday = {}
			@wednesday.compare_by_identity
			@thursday = {}
			@thursday.compare_by_identity
			@friday = {}
			@friday.compare_by_identity
			@saturday = {}
			@saturday.compare_by_identity
			@sunday = {}
			@sunday.compare_by_identity
			events.each do |e|
				day_name = e.date.strftime('%A')
				case day_name
				when "Monday"
					@monday["name"] = e.name
					@monday["description"] = e.description
					@monday["date"] = e.date
				when "Tuesday"
					@tuesday["name"] = e.name
					@tuesday["description"] = e.description
					@tuesday["date"] = e.date
				when "Wednesday"
					@wednesday["name"] = e.name
					@wednesday["description"] = e.description
					@wednesday["date"] = e.date
				when "Thursday"
					@thursday["name"] = e.name
					@thursday["description"] = e.description
					@thursday["date"] = e.date
				when "Friday"
					@friday["name"] = e.name
					@friday["description"] = e.description
					@friday["date"] = e.date
				when "Saturday"
					@saturday["name"] = e.name
					@saturday["description"] = e.description
					@saturday["date"] = e.date
				else
					@sunday["name"] = e.name
					@sunday["description"] = e.description
					@sunday["date"] = e.date
 				end

			end
	end
end

app/controllers/special_interest_controller.rb
class SpecialInterestController < ApplicationController
	def special_interest_page
		
		$events = Event.all.order("date ASC")
		$rate_e = RateEvent.all
	end

	def rate_event
		event_id = params[:event_id]
    note = params[:note]
    r = RateEvent.where(:event_id => event_id, :user_id => current_user)
    if r.empty? 
    	RateEvent.create(:note => note, :event_id => event_id, :user_id => current_user.id )
    else
     r[0].update(:note => note)
    end
   render :nothing => true
	end

	def rate_event_value
    event_id = params[:event_id]

    r = RateEvent.where(:event_id => event_id)
    if !r.empty? 
      a = 0 
      n = 0
      r.each do |h|
        a += h.note
        n +=1 
      end
      respond_to do |format|
        format.js {render :json => {"note"=> a/n}}
      end
    end
  end
end

app/helpers/about_romania_helper.rb
module AboutRomaniaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/multimedia_helper.rb
module MultimediaHelper
end

app/helpers/special_interest_helper.rb
module SpecialInterestHelper
end

app/helpers/trip_planner_helper.rb
module TripPlannerHelper
end

app/helpers/what_to_do_helper.rb
module WhatToDoHelper
end

app/views/special_interest/_architecture.html.erb
<h2> Architecture </h2>
		<section class="content row">

			<div class="col-lg-5">
				<img class="traditions" src="assets/Architecture/Casa_Poporului_1.jpg" alt="" >	
			</div>

			<div class="col-lg-7">
				<h3>Palace of the Parliament</h3>
				<p>

					Constructing the Palace and Centrul Civic required demolishing much of Bucharest's historic district, including 19 Orthodox Christian churches, six Jewish synagogues, three Protestant churches (plus eight relocated churches), and 30,000 residences.
				</p>
			</div>
		</section>


		<section class="content row">
		

			<div class="col-lg-7">
				<h3>The Painted Monasteries of Bucovina</h3>
				<p>
					It was during his time that the Moldavian style, of great originality and stylistic unity, developed, by blending Gothic elements with the Byzantine structure specific to the churches. Among such constructions, the monumental church of the Neamţ Monastery served, for more than a century, as a model for Moldavian churches and monasteries. The style was continued in the 16th century, during the rule of Stephen the Great's son, Petru Rareş (1527–1538, 1541–1546).
				</p>
				<p>
					 The main innovation was the porch and the outwall paintings (the churches of Voroneţ, Suceviţa, Moldoviţa monasteries). These churches of Northern Moldavia have become famous worldwide, due to the beauty of their painted elegant shapes that can be seen from afar.
				</p>
			</div>
	<div class="col-lg-5">
				<img class="traditions" src="assets/Architecture/Manastirea_Sucevita_2.jpg" alt="" >	
			</div>

		</section>

		<section class="content row">

			<div class="col-lg-5">
				<img class="traditions" src="assets/Architecture/Castelul_Bran_1.jpg" alt="" >	
			</div>

			<div class="col-lg-7">
				<h3>Bran Castle</h3>
				<p>
					Bran Castle – a remarkable gothic architectural design monument was built between 1377-1382 on a 60 m cliff as a result of privilege from November 19, 1377 the Hungarian king Louis I of Anjou. Once the point has been reinforced by fulfilling military functions appearing awake and southeastern Transylvania but also have customs and trade functions are located on the commercial road connecting Transylvania with Wallachia Rucăr-Bran in Romania. Dracula Castle Bran Castle is known as one of the most precious historical sites in Transylvania.
				</p>
			</div>
		</section>


		<section class="content row">
		

			<div class="col-lg-7">
				<h3>Peles Castle</h3>
				<p>
					Inaugurated in 1883, Peles Castle is not only a pleasant place during the summer day; it has been conceived to be also a national monument, meant to keep the trophies of the Plevna Victory, which explains the castle´s majestic style.
				</p>
				<p>
					Peles Castle was built in wood, stone, bricks and marble and comprises more than 160 rooms. The representative style used is German Renaissance, but one can easily discover elements belonging to the Italian Renaissance, Gothic, German Baroque and French Rococo style.
				</p>
			</div>
	<div class="col-lg-5">
				<img class="traditions" src="assets/Architecture/Castelul_Peles_3.jpg" alt="" >	
			</div>

		</section>

		<section class="content row">

			<div class="col-lg-5">
				<img class="traditions" src="assets/Architecture/Mogosoaia_Palace_front.jpg" alt="" >	
			</div>

			<div class="col-lg-7">
				<h3>Mogosoaia Palace</h3>
				<p>
					The Palace was built by the ruler Constantin Brancoveanu in 1702. After the execution of Constantin Brancoveanu in Constantinopol in 1714, the palace continue to be own by the family, but has passed a decline during the Ottoman rule period. It was renovated starting with 1912 by Martha Bibescu becoming a meeting place for the members in the high level society.
				</p>
				<p>
					The Brâncovenesc style, also known as Wallachian Renaissance and Romanian Renaissance, is an art and architectural style that evolved during the administration of Prince Constantin Brâncoveanu in the late 17th and early 18th centuries. Brâncoveanu was an administrator of the Principality of Wallachia (c. 1400 - 1829) under Ottoman Empire overlords, an extremely wealthy aristocrat, and a builder of fine palaces and churches.
				</p>
			</div>
		</section>


		<section class="content row">
		
			
			<div class="col-lg-7">
				<h3>C.E.C. Palace</h3>
				<p>
					The palace was built as a new headquarters for Romania's oldest bank, the public savings institution Casa de Depuneri, Consemnațiuni și Economie, later known as C.E.C. The land was bought and the building constructed with the institution's own funds. Work started on June 8, 1897 and was completed in 1900. The project was designed by the architect Paul Guttereau, a graduate of the École nationale supérieure des Beaux-Arts in Paris; construction was supervised by the Romanian architect Ion Socolescu.
				</p>
				<p>
					Built in eclectic style, the palace is topped by a glass and metal dome. The entrance features an arch supported by two pairs of columns in composite style. The four corners are decorated with gables and coats of arms and ending in Renaissance domes.
				</p>
			</div>
	<div class="col-lg-5">
				<img class="traditions" src="assets/Architecture/Bucharest_CEC.jpg" alt="" >	
			</div>

		</section>

		<section class="content row">

			<div class="col-lg-5">
				<img class="traditions" src="assets/Architecture/Corvin_Castle.jpg" alt="" >	
			</div>

			<div class="col-lg-7">
				<h3>Corvin Castle</h3>
				<p>
					The greatest Gothic-style castle in Romania, Corvinesti was built by the Anjou family on the site of a former Roman camp. The castle served as a fortress until the mid-14th century when it became the residence of Transylvania's ruler, Iancu de Hunedoara. Iancu upgraded the fortress transforming it into the most stunning castle in Transylvania.
				</p>
				<p>
					The beautifully preserved structure features a sumptuous Knights' Hall, an impressive drawbridge, high buttresses, inner courtyards, a chapel and some 50 rooms resplendent with medieval art. The courtyard features a 100 ft. well dug into stone.
				</p>
			</div>
		</section>


	

app/views/special_interest/_count_dracula.html.erb
<h2>Count Dracula Legend</h2>

app/views/special_interest/_festivals_events.html.erb
<h2>Festivals & Events</h2>


	<% $events.each_slice(2) do |e1,e2| %>
		
			<section class="content row right_event">

				<div class="col-lg-5">
					<img class="events" src="assets/events/<%= e1.id %>.jpg" alt="" >	
				</div>

				<div class="col-lg-7 event_description">
					<section class="content row rate_event_">
						<div class="col-lg-9">
							<h3 class="title_"><%= e1.name  %></h3>
						</div>
						<div class="col-lg-3">
							<% rate = $rate_e.where(event_id: e1.id) %>
							<% n = rate.length %>
							<% s = 0 %>
							<% note = 0 %>
								<% rate.each do |r| %>
									<% s+=r.note %>
								<% end %>

							<% if s>0 %>
							<% note = s/n %>
							
							<% end %>
							<section class="global_star_<%= e1.id %> ">
							<% if note ==0  %>
								<% (1..5).each do |i| %>
									<li class="rating_star_event " data-event-id="<%= e1.id %>" data-stars= "<%= i %>" id="s_<%= e1.id.to_s + '_'+ i.to_s %>"></li>
								<% end %>
							<% else %>
								
									<% (1..note).each do |i| %>
										<li class="rating_star_event on " data-event-id="<%= e1.id %>" data-stars= "<%= i %>"	id="s_<%= e1.id.to_s + '_'+ i.to_s %>"></li>
									<% end %>
								<% if note < 5 %>
									<% (note+1..5).each do |i| %>
										<li class="rating_star_event " data-event-id="<%= e1.id %>" data-stars= "<%= i %>" id="s_<%= e1.id.to_s + '_'+ i.to_s %>"></li>
									<% end %>
								<% end %>
							
								
							<% end %> <!-- if note == 0 -->
						</section>
						</br>
						<% if current_user %>





















								<% verif = $rate_e.where(event_id: e1.id, user_id: current_user.id) %>
								<% if verif.empty? %>
									<% (1..5).each do |i| %>
										<li class="rating_star_event_active " data-event-id="<%= e1.id %>" data-stars= "<%= i %>" id="<%= e1.id.to_s + '_'+ i.to_s %>"></li>
									<% end %>

								<% else %>
									<% note_user = verif[0].note %>

									<% (1..5).each do |i| %>
										<% if i<= note_user %>
										<li class="rating_star_event_active on" data-event-id="<%= e1.id %>" data-stars= "<%= i %>" id="<%= e1.id.to_s + '_'+ i.to_s %>"></li>
										<% else %>
										<li class="rating_star_event_active" data-event-id="<%= e1.id %>" data-stars= "<%= i %>" id="<%= e1.id.to_s + '_'+ i.to_s %>"></li>
										<% end %> <!-- i<=note_user -->
									<% end %>

								<% end %> <!-- verif.empty? -->
						


							<% end %> <!-- current_user -->

						</div> <!-- col-lg-3 -->
					</section>

					<p>
						<%= e1.description  %>
					</p>
		
				
				</div>
			</section>

			<section class="content row left_event">
			

				<div class="col-lg-7 event_description">

					<section class="content row rate_event_">
						<div class="col-lg-9">
							<h3 class="title_"><%= e2.name  %></h3>
						</div>
						<div class="col-lg-3">
							<% rate = $rate_e.where(event_id: e2.id) %>
							<% note = 0 %>
							<% n = rate.length %>
							<% s = 0 %>
								<% rate.each do |r| %>
									<% s+=r.note %>
								<% end %>

							<% if s>0 %>
							<% note = s/n %>
							
							<% end %>
							<section class="global_star_<%= e2.id %> ">
							<% if note ==0  %>
								<% (1..5).each do |i| %>
									<li class="rating_star_event " data-event-id="<%= e2.id %>" data-stars= "<%= i %>"
									id="s_<%= e2.id.to_s + '_'+ i.to_s %>"></li>
								<% end %>
							<% else %>
								
									<% (1..note).each do |i| %>
										<li class="rating_star_event on " data-event-id="<%= e2.id %>" data-stars= "<%= i %>"	id="s_<%= e2.id.to_s + '_'+ i.to_s %>"></li>
									<% end %>
								<% if note < 5 %>
									<% (note+1..5).each do |i| %>
										<li class="rating_star_event " data-event-id="<%= e2.id %>" data-stars= "<%= i %>" id="s_<%= e2.id.to_s + '_'+ i.to_s %>"></li>
									<% end %>
								<% end %>
							
								
							<% end %> <!-- if note == 0 -->
						</section>
							</br>
							<% if current_user %>
								<% verif = $rate_e.where(event_id: e2.id, user_id: current_user.id) %>
								<% if verif.empty? %>
									<% (1..5).each do |i| %>
										<li class="rating_star_event_active " data-event-id="<%= e2.id %>" data-stars= "<%= i %>" id="<%= e2.id.to_s + '_'+ i.to_s %>"></li>
									<% end %>










								<% else %>
									<% note_user = verif[0].note %>

									<% (1..5).each do |i| %>
										<% if i<= note_user %>
										<li class="rating_star_event_active on" data-event-id="<%= e2.id %>" data-stars= "<%= i %>" id="<%= e2.id.to_s + '_'+ i.to_s %>"></li>
										<% else %>
										<li class="rating_star_event_active" data-event-id="<%= e2.id %>" data-stars= "<%= i %>" id="<%= e2.id.to_s + '_'+ i.to_s %>"></li>
										<% end %> <!-- i<=note_user -->
									<% end %>

								<% end %> <!-- verif.empty? -->
						


							<% end %> <!-- current_user -->

						</div> <!-- col-lg-3 -->
					</section>					
			
					</br>
					<p>
						<%= e2.description  %>
					</p>


				</div>
				<div class="col-lg-5">
					<img class="events" src="assets/events/<%= e2.id %>.jpg" alt="" >	
				</div>

			</section>



	<% end %> <!-- $events -->
			<script src="assets/myscrypt.js" type="text/javascript"></script>

app/views/special_interest/_food_wine.html.erb
<h2>Food & Wine</h2>


		<section class="content row">

			<div class="col-lg-5">
				<img class="traditions" src="assets/food&wine/Ciorba de burta.jpg" alt="" >	
			</div>

			<div class="col-lg-7">
				<h3>Tripe soup</h3>
			<p>
				When it comes to Romanian traditional foods, 2 courses are most popular among both Romanians and foreigners: the “sarmale with mamaliga” and the “ciorba de burta” ( tripe soup). And although the tripe soup is considered by many to be the tastiest of the Romanian soups, the travellers don’t really want to try it because of what is inside – of course, if they just try it without knowing what it is, the absolutely love it! 
			</p>
			</div>
		</section>


		<section class="content row">
		

			<div class="col-lg-7">
				<h3>Beans with sausages</h3>
				<p>
					On December 1st it’s served ”beans with sausages”, a traditional Romanian food. So every Romanian woman has to know how to cook it. And obviously there are many recipes, each with its style. I'll show you a very special recipe, very tasty, one that will make you feel proud in front of foreign guests (if they want a traditional Romanian dish). 
				</p>
				
			</div>
	<div class="col-lg-5">
				<img class="traditions" src="assets/food&wine/Fasole cu carnati.jpg" alt="" >	
			</div>

		</section>



		<section class="content row">

			<div class="col-lg-5">
				<img class="traditions" src="assets/food&wine/Sarmalute.jpg" alt="" >	
			</div>

			<div class="col-lg-7">
				<h3>Sarmale</h3>
				<p>
					Sarma is a dish of grape, cabbage or chard leaves rolled around a filling usually based on minced meat, or a sweet dish of filo dough wrapped around a filling often of various kinds of chopped nuts. It is found in the cuisines of the former Ottoman Empire from the Middle East to the Balkans and Central Europe.
				</p>
			</div>
		</section>


		<section class="content row">
		

			<div class="col-lg-7">
				<h3>Clatite (Crepes)</h3>
			<p>
				Thin, French-style pancakes are popular throughout Eastern Europe and are known variously as palacinke in Serbia and Croatia, palacsintas in Hungary and nalesniki in Polish, and so on. In Romania, crepes are known as clătite. Depending on the filling, they can be served as an appetizer, meal or dessert. 
			</p>
			</div>
	<div class="col-lg-5">
				<img class="traditions" src="assets/food&wine/Clatite.jpg" alt="" >	
			</div>

		</section>

		<section class="content row">
			<div class="col-lg-5">
				<img class="traditions" src="assets/food&wine/Kurtos.jpg" alt="" >	
			</div>

			<div class="col-lg-7">
				<h3>Kurtos colac</h3>
			<p>
				A long rope of sweet yeast dough is tightly wrapped in a spiral around a wooden form, something like a rolling pin, and dusted with sugar.  It is then baked, slowly turning, on a rotating spit above an open flame.  Carefully edged off its wooden mold after baking, each chimney cake is a whimsical-looking, soft bread with an addictively crunchy caramelized sugar crust and an airy open center.    
			</p>
			
			</div>


		</section>


		<section class="content row">
		

			<div class="col-lg-7">
				<h3>Mititei</h3>
				<p>
					Mititei ( or mici, both Romanian words meaning "small things") is a traditional Romanian dish of grilled ground meat rolls made from a mixture of beef, lamb and pork and spices such as garlic, black pepper, thyme, coriander, anise, savory and sometimes a touch of paprika. Sodium bicarbonate and broth or water are also added to the mixture. It is best served accompanied by mustard and beer. Ideally the mustard should not be overly tart, lest it interferes with the taste of the mititei. The dish is very popular in Romania.
				</p>
			</div>
	<div class="col-lg-5">
				<img class="traditions" src="assets/food&wine/Mici.jpg" alt="" >	
			</div>

		</section>

			<section class="content row">

			<div class="col-lg-5">
				<img class="traditions" src="assets/food&wine/Cheese.jpg" alt="" >	
			</div>

			<div class="col-lg-7">
				<h3>Cheese</h3>
				<p>
					Cheese and tree bark don't seem like a natural fit. But this specialty of southeast Transylvania, especially in the towns and villages that include Moeciu and Fundata, may go as far back as the 14th century. Dairy farmers needed a way to store the surplus cheese, and the local evergreen forests provided the perfect vehicle. After all, woody bark provides wonderful protection for trees. Strip the bark from a fir tree, wrap it around the cheese and presto: the dairy product remains moist and preserved from the elements. 
				</p>
			</div>
		</section>


			<section class="content row">

			

			<div class="col-lg-7">
				<h3>Wine</h3>
				<p>
					Romania is one of the world's largest wine producers, producing (as of 2009) around 610,000 tons of wine. In recent years, Romania has attracted many European business people and wine buyers, due to the affordable prices of both vineyards and wines compared to other wine producing nations such as France, Germany, and Italy. Romania has one of the oldest wine making traditions in the world, its viticulture dating back more than 6000 years. Due to the hot dry summers, the location proved to be successful and the grape vineyards thrived. Since the medieval times, wine has been the traditional alcoholic beverage of the Romanians.
				</p>
			</div>

			<div class="col-lg-5">
				<img class="traditions" src="assets/food&wine/vin-murfatlar.jpg" alt="" >	
			</div>
		</section>

app/views/special_interest/_shopping.html.erb
<h2>Shopping</h2>

app/views/special_interest/architecture.js.erb
$('.main_container').empty();
$('.main_container').append("<%=j render 'architecture' %>");

app/views/special_interest/count_dracula.js.erb
$('.main_container').empty();
$('.main_container').append("<%=j render 'count_dracula' %>");

app/views/special_interest/festivals_events.js.erb
$('.main_container').empty();
$('.main_container').append("<%=j render 'festivals_events' %>");

app/views/special_interest/food_wine.js.erb
$('.main_container').empty();
$('.main_container').append("<%=j render 'food_wine' %>");

app/views/special_interest/shopping.js.erb
$('.main_container').empty();
$('.main_container').append("<%=j render 'shopping' %>");

app/views/special_interest/special_interest_page.html.erb
		<div class = "container" id="specialinterest">

			<section class="content row">
				<div class="col-lg-12">
					<header class="clearfix">
						<section id="branding" class="brand">
							<a href="index.html"><img src="assets/romania-branding.png" alt="Logo for Romania" style="max-width:100%"></a>
						</section>
						<%= render "components/header" %>

					</header> <!--clearfix-->
				</div><!--column-->
			</section><!--content row-->
<section class="container">
<div class="content row ">
	<section class="col-lg-12 main_container">

							<h2>Special Interest</h2>
							<p>This website is intended to assist travelers who are planning to visit Romania or would like
to learn more about Romania.
Authentic, Natural and Cultural are the words that best capture the essence of Romania,
a dynamic country rich in history, arts and scenic beauty.
Romania offers countless unique travel experiences that are waiting to be discovered.
</p>
	<div class="content row my_content">
	<div class="col-lg-6 img_text left">
	<div class="fluid">
				<div class="top">
					<img src="">
				</div>
				<img class="center_img" src="assets/Painted_Eggs_tn.jpg" alt="Traditions & Folklore" />
				<section class="inner">
					
					<%= link_to 'Tradition & Folklore', traditions_folklore_path, :remote => true, :class => "img_title"%>
							<p>The countryside is the heart and soul of Romania, where peasant culture remains a strong force and medieval life prevails, as it does nowhere else in Europe.</p>
				</section>
				<div class="clear foot">
					<img src="">
				</div>
			</div>
</div>

<div class="col-lg-6 img_text">
	<div class="fluid">
				<div class="top">
					<img src="">
				</div>
				<img class="center_img" src="assets/Sighisoara_Medieval_Festival_tn.jpg" alt="Festivals & Events" />
				<section class="inner">
					<%= link_to 'Festivals & Events', festivals_events_path, :remote => true, :class => "img_title" %>
							<p>Throughout the year, Romanians celebrate their ancient heritage, changing seasons, religious holidays and life-cycle events, such as birth, marriage and death,
with festivals that have remained unchanged for centuries</p>
				</section>
				<div class="clear foot">
					<img src="">
				</div>
			</div>
</div>
</div>
<div class="content row my_content">

<div class="col-lg-6 img_text left">
	<div class="fluid">
				<div class="top">
					<img src="">
				</div>
				<img class="center_img" src="assets/Wine_tn.jpg" alt="Food & Wine" />
				<section class="inner">
					<%= link_to 'Food & Wine', food_wine_path, :remote => true, :class => "img_title" %>
							<p>The central characteristic of the Romanian cuisine is its
great variety. It is a cuisine influenced by repeated waves of different cultures</p>
				</section>
				<div class="clear foot">
					<img src="">
				</div>
			</div>
</div>

<div class="col-lg-6 img_text">
	<div class="fluid">
				<div class="top">
					<img src="">
				</div>
				<img class="center_img" src="assets/Mogosoaia_Palace_tn.jpg" alt="Architecture" />
				<section class="inner">
					<%= link_to 'Architecture', architecture_path, :remote => true, :class => "img_title" %>
							<p>Monasteries, churches, synagogues, castles and palaces throughout the country, some dating from the 12th Century, depict the country's tumultuous history</p>
				</section>
				<div class="clear foot">
					<img src="">
				</div>
			</div>
</div>

</div>



	</section>

</div>

</section>




		

		</div><!--container-->

app/views/special_interest/traditions_folklore.js.erb
$('.main_container').empty();
$('.main_container').append("<%=j render 'traditions_folklore' %>");