config/routes.rb
Site::Application.routes.draw do

    get 'auth/:provider/callback', to: 'sessions#create'
    get 'auth/failure', to: redirect('/')
    get 'signout', to: 'sessions#destroy', as: 'signout'

    root to: 'home#home_page'

    get 'about_romania', to: 'about_romania#about_page'
    get 'destinations', to: 'destinations#destinations_page'
    get 'multimedia', to: 'multimedia#multimedia_page'
    get 'special_interest', to: 'special_interest#special_interest_page'
    get 'trip_planner', to: 'trip_planner#trip_planner_page'
    get 'what_to_do', to: 'what_to_do#what_to_do_page'
    
    match '/destinations/top' => 'destinations#top', :as => 'top', :via => :get

    match '/destinations/comment/:clas/:loc' => 'destinations#comment', :as => 'comments', :via => :get
    match '/destinations/comment/:clas/:loc' => 'destinations#create', :via => :post

    match '/destinations/rate_loc/:location_id/:note' => 'destinations#rate_loc', :via => :post
     match '/destinations/rate_loc/:location_id' => 'destinations#rate_loc_value', :via => :get
    match '/destinations/cities' => 'destinations#cities', :as => 'cities', :via => :get
    match '/destinations/castles' => 'destinations#castles', :as => 'castles', :via => :get
    match '/destinations/regions' => 'destinations#regions', :as => 'regions', :via => :get
    match '/destinations' => 'destinations#topdestination', :as => 'topdestination', :via => :get

    match '/special_interest/architecture' => 'special_interest#architecture', :as => 'architecture', :via => :get
  
    match '/special_interest/festivals_events' => 'special_interest#festivals_events', :as => 'festivals_events', :via => :get
    match '/special_interest/food_wine' => 'special_interest#food_wine', :as => 'food_wine', :via => :get
    match '/special_interest/traditions_folklore' => 'special_interest#traditions_folklore', :as => 'traditions_folklore', :via => :get
    match '/special_interest/rate_event/:event_id/:note' => 'special_interest#rate_event',  :via => :post
     match '/special_interest/rate_event/:event_id' => 'special_interest#rate_event_value', :via => :get

    
    match '/trip_planner/entry_requirements' => 'trip_planner#entry_requirements', :as => 'entry_requirements', :via => :get
    match '/trip_planner/itinerary_ideas' => 'trip_planner#itinerary_ideas', :as => 'itinerary_ideas', :via => :get
    match '/trip_planner/practical_information' => 'trip_planner#practical_information', :as => 'practical_information', :via => :get
    match '/trip_planner/transportation' => 'trip_planner#transportation', :as => 'transportation', :via => :get

  

end

app/models/castle.rb
class Castle < ActiveRecord::Base 
	belongs_to :location
end

app/models/city.rb
class City < ActiveRecord::Base
	belongs_to :location
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	has_many :users
	has_many :locations
	validates :com_text, presence: true
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :rate_event
	has_one :location
end

app/models/event_address.rb
class EventAddress < ActiveRecord::Base
	belongs_to :location
end

app/models/event_comment.rb
class EventComment < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
	has_many :top_destinations
	has_many :cities
	has_many :castles
	has_many :regions
	has_many :event_addresses
	belongs_to :rate_location
	belongs_to :comment
	belongs_to :event
end

app/models/rate_event.rb
class RateEvent < ActiveRecord::Base
	has_many :users
	has_many :events
end

app/models/rate_location.rb
class RateLocation < ActiveRecord::Base
	has_many :locations
	has_many :users
end

app/models/region.rb
class Region < ActiveRecord::Base
	belongs_to :location
end

app/models/top_destination.rb
class TopDestination < ActiveRecord::Base
	belongs_to :location
end

app/models/user.rb
class User < ActiveRecord::Base
	def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
  belongs_to :rate_location
  belongs_to :rate_event
  belongs_to :comment
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def home_page
			events = Event.all.order("date ASC")
			@monday = {} 
			@monday.compare_by_identity
			@tuesday = {}
			@tuesday.compare_by_identity
			@wednesday = {}
			@wednesday.compare_by_identity
			@thursday = {}
			@thursday.compare_by_identity
			@friday = {}
			@friday.compare_by_identity
			@saturday = {}
			@saturday.compare_by_identity
			@sunday = {}
			@sunday.compare_by_identity
			events.each do |e|
				day_name = e.date.strftime('%A')
				case day_name
				when "Monday"
					@monday["name"] = e.name
					@monday["description"] = e.description
					@monday["date"] = e.date
				when "Tuesday"
					@tuesday["name"] = e.name
					@tuesday["description"] = e.description
					@tuesday["date"] = e.date
				when "Wednesday"
					@wednesday["name"] = e.name
					@wednesday["description"] = e.description
					@wednesday["date"] = e.date
				when "Thursday"
					@thursday["name"] = e.name
					@thursday["description"] = e.description
					@thursday["date"] = e.date
				when "Friday"
					@friday["name"] = e.name
					@friday["description"] = e.description
					@friday["date"] = e.date
				when "Saturday"
					@saturday["name"] = e.name
					@saturday["description"] = e.description
					@saturday["date"] = e.date
				else
					@sunday["name"] = e.name
					@sunday["description"] = e.description
					@sunday["date"] = e.date
 				end

			end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to_back
  end

  def destroy
    session[:user_id] = nil
    redirect_to_back
  end

  private 
   def redirect_to_back(default = root_url)
    if !request.env["HTTP_REFERER"].blank? and request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]
      redirect_to :back
    else
      redirect_to default
    end
  end
end

app/controllers/trip_planner_controller.rb
class TripPlannerController < ApplicationController
	def trip_planner_page
	 	
	 end 
end

app/helpers/about_romania_helper.rb
module AboutRomaniaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/multimedia_helper.rb
module MultimediaHelper
end

app/helpers/trip_planner_helper.rb
module TripPlannerHelper
end

app/helpers/what_to_do_helper.rb
module WhatToDoHelper
end

app/views/trip_planner/_accommodations.html.erb
<h2>Distinctive Accommodations</h2>

app/views/trip_planner/_entry_requirements.html.erb
<h2>Entry Requirements</h2>

app/views/trip_planner/_getting_here.html.erb
<h2>Getting here and around</h2>

app/views/trip_planner/_itinerary_ideas.html.erb
<h2>Itinerary Ideas</h2>
<section class="itinerary">
			<div id="itineraryindex" class="row">
				<section class="scrollspy clearfix col col-lg-4 hidden-sm">
					
					<ul class="nav nav-list affix">
						<li><a href="#bucharest_s_transylvania">Bucharest and Southern Transylvania</a></li>
						<li><a href="#discover_walachia">Discover Walachia</a></li>
						<li><a href="#bucharest_painted_monasteries">Bucharest and the Painted Monasteries</a></li>
						<li><a href="#bucharest_budapest">Bucharest to Budapest (Hungary )</a></li>
						<li><a href="#villages_maramures">The traditional Villages of Maramures</a></li>
						<li><a href="#danube_delta">The Danube Delta – Europe ’s Everglades</a></li>
					
					</ul><!-- nav-list -->
				</section><!-- scrollspy -->
				
				<section class="itineraryinfo col col-lg-8">
				<article class="media" id="bucharest_s_transylvania">
					<h3> Bucharest and Southern Transylvania</h3>
					<p>
						<strong>Itinerary:</strong> 
					Bucharest - Sinaia - Brasov - Sighisoara - Sibiu
					</br>
					<strong>Duration: </strong>
					5 days
					</br>
					<strong>Best way of transportation:</strong>
					 train or car
					</p>
					<p>
						<strong>» Day 1: Bucharest</strong>
						Explore Bucharest, the capital of Romania. In the evening enjoy a concert by George Enescu Philharmonic Orchestra or travel to Valea Calugareasca, one of the top Romanian wine regions. After wine tasting and dinner return to Bucharest.
					</p>
					<p>
						<strong>» Day 2: Bucharest - Sinaia - Brasov (103 miles/ 166 km)</strong>
						Drive or take the train to Sinaia and visit the Peles Castle. Built in 1883, Peles Castle is a masterpiece of German Renaissance architecture. The smaller Pelisor Castle features a unique collection of Viennese furniture and Tiffany glassware. Continue straight to Brasov or from Predeal take a 25 miles detour to the village of Bran to visit the 14th century Bran (Dracula’s) Castle then continue to Brasov. Overnight in Brasov.
					</p>
					<p>
						<strong>» Day 3: Brasov - Sighisoara (72 miles/ 116 km)</strong>
						Sightseeing in Brasov. Highlights include: the Council Square, the beautiful Saint Nicholas Church, Brasov Fortress, Franciscan Monastery. Do not miss the Black Church whose name is attributed to a fire set in 1689 by disgruntled invaders unable to breach the city’s walls. Ever since, the church and its red-tiled roof have been ash-stained. For a panoramic view of Brasov and the surrounding Carpathians Mountains take the cable car to Postavarul Peak in Poiana Brasov.
					</p>
					<p>
						<strong>» Day 4: Day-trip to Sibiu (110 miles/ 178 km)</strong>
						Sightseeing in Sibiu. Highlights include: Craftsmen’s Square, Huet Square and Evangelical Church, Bridge of Lies, Goldsmith Square, Great Square, Orthodox Cathedral, Roman Catholic Church, City Hall Tower. Take an afternoon train/ drive back to Sighisoara or continue to Brasov. Overnight in Sighisoara or in Brasov.
					</p>
					<p>
						<strong>» Day 5: Return to Bucharest (175 miles/ 282 km)</strong>
						or continue your journey to the Painted Monasteries in Bucovina.
					</p>

				</article>

				<article class="media" id="discover_walachia">
					<h3>Discover Walachia</h3>
					<p>
						<strong>Itinerary: </strong>
						Bucharest - Targoviste - Curtea de Arges - Brasov - Sinaia - Bucharest
						<strong>Duration:</strong>
						 5 days
						<strong>Best way of transportation: </strong>
						 car
					</p>
					<p>
						<strong>» Day 1: Bucharest</strong>
						Explore Bucharest, the capital of Romania. Overnight in Bucharest.
					</p>
					<p>
						<strong>» Day 2: Bucharest - Targoviste - Curtea de Arges (118 miles/ 191 km)</strong>
						Drive to Targoviste and visit the Princely Court (the authentic Dracula’s Castle). From Targoviste continue to Curtea de Arges to visit the 16th century Curtea de Arges Monastery (Manastirea Curtea de Arges) and the 14th century Princely Court (Curtea Domneasca). Overnight in Curtea de Arges.
					</p>
					<p>
						<strong>» Day 3: Curtea de Arges - Campulung - Bran - Brasov(81 miles/ 131 km)</strong>
						From Curtea de Arges to Bran, drive over the Carpathian Mountains (through Bran-Rucar Pass). Visit Bran (Dracula’s) Castle. Spend a night in a private farm and enjoy homemade cheeses and grilled lamb pastrami or continue to Brasov (16 miles northeast).
					</p>
					<p>
						<strong>» Day 4: Brasov</strong>
						Stroll around Brasov’s medieval section and learn about the city’s rich history. Overnight in Brasov.
					</p>
					<p>
						<strong>» Day 5: Brasov - Sinaia - Bucharest (103 miles/ 166 km)</strong>
						Return to Bucharest via Sinaia, where Peles Castle, former summer residence of the Royal family, awaits. Wine enthusiasts can stop in the town of Azuga for lunch and wine tasting at Rhein Cellars.
					</p>
				</article>
				
				<article class="media" id="bucharest_painted_monasteries">
					<h3>Bucharest and the Painted Monasteries</h3>
					<p>
						<strong>Itinerary: </strong>
						Bucharest - Suceava - Sighisoara - Brasov - Sinaia
						<strong>Duration: </strong>
						5 days 
						<strong>Best way of transportation: </strong>
						 car or train and car
					</p>
					<p>
						<strong>» Day 1: Bucharest to Suceava (282 miles/ 455 km)</strong>
						Travel from Bucharest to Suceava - by express train (6 hours) or by car. Overnight in Suceava or in Gura Humorului. There are also non-stop flights from Bucharest or from Vienna (Austria) to Iasi (90 miles southeast of Suceava).
					</p>
					<p>
						<strong>» Day 2: The Painted Monasteries (108 miles/ 175 km)</strong>
						Visit the unique monasteries of Bucovina: Voronet, Sucevita, Moldovita and Humor (car rental or tour/ transportation arranged locally).
					</p>
					<p>
						<strong>» Day 3: Return to Bucharest or Vienna</strong>
						Travel to Suceava or Iasi for your flight back home
						or continue to Bucharest on land, crossing Transylvania:
						The Painted Monasteries – Sighisoara (182 miles/ 294 km) Take the scenic route to Sighisoara via Bicaz Gorges. En route to Sighisoara stop in Corund and visit the local pottery workshops. Overnight in Sighisoara.
					</p>
					<p>
						<strong>» Day 4: Sighisoara - Brasov (72 miles/ 116 km)</strong>
						Sightseeing in Sighisoara, one of the best-preserved medieval towns in Europe. Spend the day seeing the sights, such as the Clock Tower, Church on the Hill, Scholars’ Wooden Staircase, Venetian House, Hermann Oberth Square. Travel to Brasov (train or car). Overnight in Brasov.
					</p>
					<p>
						<strong>» Day 5: Brasov to Bucharest (103 miles/ 166 km)</strong>
						Take the train or drive to Bucharest. En route to Bucharest stop in Sinaia to visit the Peles Castle.
					</p>
				</article>
				<article class="media" id="bucharest_budapest">
					<h3> Bucharest to Budapest (Hungary )</h3>
					<p>
						<strong>Itinerary: </strong>
						Bucharest - Brasov - Sighisoara - Cluj - Oradea - Budapest 
						<strong>Duration: </strong>
						5 days 
						<strong>Best way of transportation: </strong>
						car or train

					</p>
					
					<p>
						<strong>» Day 1: Bucharest - Sinaia - Brasov (103 miles/ 166 km)</strong>
						Travel from Bucharest to Sinaia and visit the Peles Castle. Continue to Brasov and see its Gothic, Baroque and Renaissance buildings, among other sights. Overnight in Brasov.
					</p>
					<p>
						<strong>» Day 2: Brasov - Sighisoara (72 miles/ 116km)</strong>
						Travel to Sighisoara; see one of Europe’s best-preserved medieval towns. Overnight in Sighisoara.
					</p>
					<p>
						<strong>» Day 3: Sighisoara - Cluj-Napoca (100 miles/ 162 km)</strong>
						Travel to Cluj-Napoca. Discover the city’s architecture. See paintings dating from the Middle Ages housed in the 18th-century Banffy Palace. Learn about the region at the Ethnographic Museum of Transylvania. Overnight in Cluj- Napoca.
					</p>
					<p>
						<strong>» Day 4: Cluj-Napoca - Oradea (95 miles/ 153 km)</strong>
						Drive or take the train to Oradea, a city known for its Art Nouveau architecture. Visit the “Church with Moon” and Museum of the Cris Rivers, housed in a 1770 Baroque palace. Overnight in Oradea.
					</p>
					<p>
						<strong>» Day 5: Oradea to Budapest (Hungary) (155 miles/ 250 km)</strong>
						Take the train to Budapest and explore the capital of Hungary or discover the traditional villages of Maramures.
					</p>
				</article>
				<article class="media" id="villages_maramures">
					<h3> The traditional Villages of Maramures</h3>
					<p>
						<strong>Itinerary: </strong>
						 Budapest - Oradea - Satu Mare - Maramures villages
						<strong>Duration: </strong>
						4 days
						<strong>Best way of transportation: </strong>
						car or train and car
			
					</p>
					<p>
						<strong>» Day 1: Budapest - Oradea - Satu Mare (238 miles/ 384 km)</strong>
						Leave Budapest and travel to Oradea (4 hours by train). Rent a car in Oradea or hire a local guide. Travel northeast to Satu Mare. Overnight in Satu Mare. Sightseeing in Satu Mare: the impressive Secession buildings in the Great Square.
					</p>
					<p>
						<strong>» Day 2: Satu Mare - Sapanta - Botiza (94 miles/ 151 km)</strong>
						After breakfast travel east to the village of Sapanta. Sightseeing: the Merry Cemetery. Continue 12 miles east to the town of Sighetul Marmatiei. Discover Maramures’ villages such as Vadul Izei, Barsana and Botiza. In Barsana visit the workshop of master wood-carver Toader Barsan, who represented Maramures at the 2001 Smithsonian Festival in Washington, DC. Observe rural life, the traditional costumes still worn by the villagers, and the specific architecture. Overnight in a Maramures village
					</p>
					<p>
						<strong>» Day 3: Botiza - Oradea (177 miles/ 285 km)</strong>
						Sightseeing: some of the area’s wooden churches: Poienile Izei - famous for its representation of Hell on its main door, Ieud - featuring the oldest church in the entire region, Bogdan Voda and Surdesti – the tallest wooden church in the world (steeple 160 feet high). Ovenight in Oradea.
					</p>
					<p>
						<strong>» Day 4: Oradea - Budapest (155 miles/ 250 km)</strong>
						Take the train or drive from Oradea to Budapest. This itinerary can be extended with one or two days to include the Painted Monasteries in Bucovina.
					</p>
					
				</article>
				<article class="media" id="danube_delta">
					<h3>The Danube Delta – Europe ’s Everglades</h3>
					<p>
						<strong>Itinerary: </strong>
						Bucharest - Tulcea - the Danube Delta 
						<strong>Duration: </strong>
						4 days 
						<strong>Best way of transportation: </strong>
						train or car to Tulcea, then boat

					</p>
					<p>
						<strong>» Day 1: Bucharest - Tulcea - the Danube Delta (195 miles)</strong>
						Arrive in Bucharest. Transfer to Delta Nature Resort. The Delta Nature Resort is an elegant and luxurious retreat, recognized by Condé Nast Traveler as one of the Top 10 eco-resorts in the world. Sunset boat trip along meandering channels of the Danube Delta while sampling local wines from the Sarica Niculitel vineyards, such as Aligote, Feteasca Regala and Pinot Noir. Relaxed dinner at the hotel’s restaurant, overlooking Somova Lake.
					</p>
					<p>
						<strong>» Day 2: the Danube Delta</strong>
						After breakfast, head out, by boat, to Saon Monastery. Built in 1846, this religious retreat is home to some 40 nuns who run an organic farm on the banks of picturesque Lake Parcheş. Lunch, prepared by the nuns from local organic products, at the monastery. Return by boat to the hotel, via Delta channels teaming with dozens of species of birds, including the largest colony of white pelicans in Europe. Traditional Danube Delta dinner: Caviar and fresh fish from the Danube River and nearby Black Sea. On the menu will also be the delicious local salad, Salata Dobrogeana, and Saramura, an entrée prepared from broiled carp served with polenta and garlic sauce. A selection of Chardonnay, Pinot Grigio and Muscat Ottonel wines from Murfatlar vineyards will be served to quench the thirst.
					</p>
					<p>
						<strong>» Day 3: the Danube Delta</strong>
						After breakfast, explore some of the main channels and lakes of the Delta while fishing for carp, catfish, zander and perch. Hear the call of an egret, spot a group of pelicans lifting gracefully into the air or catch sight of other rare species, such as the pygmy cormorant or the red-breasted goose. For lunch sample the traditional fisherman’s soup prepared fresh in one of the villages en route. In the afternoon, visit the Danube Delta Natural History Museum in Tulcea where you will learn more about the Delta, the third most biodiverse in the world. Overnight in Tulcea.
					</p>
					<p>
						<strong>» Day 4: The Danube Delta - Tulcea - Bucharest (195 miles)</strong>
						After breakfast, departure to Bucharest for your return flight or continue your Romania Discovery Journey.
					</p>
				</article>
				</section>
			</div>
		</section>

app/views/trip_planner/_practical_information.html.erb
<h2>Practical Information</h2>

app/views/trip_planner/accommodations.js.erb
$('.main_container').empty();
$('.main_container').append("<%=j render 'accommodations' %>");

app/views/trip_planner/entry_requirements.js.erb
$('.main_container').empty();
$('.main_container').append("<%=j render 'entry_requirements' %>");

app/views/trip_planner/getting_here.js.erb
$('.main_container').empty();
$('.main_container').append("<%=j render 'getting_here' %>");

app/views/trip_planner/itinerary_ideas.js.erb
$('.main_container').empty();
$('.main_container').append("<%=j render 'itinerary_ideas' %>");

app/views/trip_planner/practical_information.js.erb
$('.main_container').empty();
$('.main_container').append("<%=j render 'practical_information' %>");

app/views/trip_planner/transportation.js.erb
$('.main_container').empty();
$('.main_container').append("<%=j render 'transportation' %>");

app/views/trip_planner/trip_planner_page.html.erb
		<div class = "container" id="tripplanner">


			<section class="content row">
				<div class="col-lg-12">
					<header class="clearfix">

						<section id="branding" class="brand">
							<a href="index.html"><img src="assets/romania-branding.png" alt="Logo for Romania" style="max-width:100%"></a>
						</section>
						<%= render "components/header" %>


					</header> <!--clearfix-->
				</div><!--column-->
			</section><!--content row-->

<section class="container">
<div class="content row ">
	<section class="col-lg-12 main_container">
							<h2>Trip Planner</h2>
							<p></p>
<div class="content row my_content">


<div class="col-lg-6 img_text left">
	<div class="fluid">
				<div class="top">
					<img src="">
				</div>
				<img class="center_img" src="assets/CFR_tn.jpg" alt="Transportation" />
				<section class="inner">
					<%= link_to 'Transportation', transportation_path, :remote => true, :class => "img_title" %>
							<p>As a densely populated country in a central location in Central-Southeastern Europe and with a developed economy, Romania has a dense and modern transportation infrastructure.</p>
				</section>
				<div class="clear foot">
					<img src="">
				</div>
			</div>
</div>

<div class="col-lg-6 img_text ">
	<div class="fluid">
				<div class="top">
					<img src="">
				</div>
				<img class="center_img" src="assets/Map_tn.jpg" alt="Itinerary Ideas" />
				<section class="inner">
					<%= link_to 'Itinerary Ideas', itinerary_ideas_path, :remote => true, :class => "img_title" %>
							<p>Starting from the capital Bucharest up to the northern border with the Ukraine, covering almost all historical regions of Romania and also most of it's interesting and unique sites, this tour offers you a glance at the best what Romania can offer. </p>
				</section>
				<div class="clear foot">
					<img src="">
				</div>
			</div>
</div>
</div>
<div class="content row my_content">





</div>


</section>


	</section>
</div>




			

		</div><!--container-->