config/routes.rb
Site::Application.routes.draw do

    get 'auth/:provider/callback', to: 'sessions#create'
    get 'auth/failure', to: redirect('/')
    get 'signout', to: 'sessions#destroy', as: 'signout'

    root to: 'home#home_page'

    get 'about_romania', to: 'about_romania#about_page'
    get 'destinations', to: 'destinations#destinations_page'
    get 'multimedia', to: 'multimedia#multimedia_page'
    get 'special_interest', to: 'special_interest#special_interest_page'
    get 'trip_planner', to: 'trip_planner#trip_planner_page'
    get 'what_to_do', to: 'what_to_do#what_to_do_page'
    
    match '/destinations/top' => 'destinations#top', :as => 'top', :via => :get

    match '/destinations/comment/:clas/:loc' => 'destinations#comment', :as => 'comments', :via => :get
    match '/destinations/comment/:clas/:loc' => 'destinations#create', :via => :post

    match '/destinations/rate_loc/:location_id/:note' => 'destinations#rate_loc', :via => :post
     match '/destinations/rate_loc/:location_id' => 'destinations#rate_loc_value', :via => :get
    match '/destinations/cities' => 'destinations#cities', :as => 'cities', :via => :get
    match '/destinations/castles' => 'destinations#castles', :as => 'castles', :via => :get
    match '/destinations/regions' => 'destinations#regions', :as => 'regions', :via => :get
    match '/destinations' => 'destinations#topdestination', :as => 'topdestination', :via => :get

    match '/special_interest/architecture' => 'special_interest#architecture', :as => 'architecture', :via => :get
  
    match '/special_interest/festivals_events' => 'special_interest#festivals_events', :as => 'festivals_events', :via => :get
    match '/special_interest/food_wine' => 'special_interest#food_wine', :as => 'food_wine', :via => :get
    match '/special_interest/traditions_folklore' => 'special_interest#traditions_folklore', :as => 'traditions_folklore', :via => :get
    match '/special_interest/rate_event/:event_id/:note' => 'special_interest#rate_event',  :via => :post
     match '/special_interest/rate_event/:event_id' => 'special_interest#rate_event_value', :via => :get

    
    match '/trip_planner/entry_requirements' => 'trip_planner#entry_requirements', :as => 'entry_requirements', :via => :get
    match '/trip_planner/itinerary_ideas' => 'trip_planner#itinerary_ideas', :as => 'itinerary_ideas', :via => :get
    match '/trip_planner/practical_information' => 'trip_planner#practical_information', :as => 'practical_information', :via => :get
    match '/trip_planner/transportation' => 'trip_planner#transportation', :as => 'transportation', :via => :get

  

end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController

	def destinations_page		

	end

  def cities
     $location = {}
    @tmp = 0
    @nr = 0

    all_table
    cities = City.all
    @hash = Gmaps4rails.build_markers(cities) do |top, marker|
      marker.infowindow render_to_string(:partial => "/destinations/infowindow", :locals => { title: top.title, description: top.address})
      marker.lat top.latitude
      marker.lng top.longitude
      marker.title top.title
    end

    respond_to do |format|
      
      
      format.js 
    end
  end


  def castles
     $location = {}
    @tmp = 0
    @nr = 0

    all_table
    castle = Castle.all
    @hash = Gmaps4rails.build_markers(castle) do |top, marker|
      marker.infowindow render_to_string(:partial => "/destinations/infowindow", :locals => { title: top.title, description: top.address})
      marker.lat top.latitude
      marker.lng top.longitude
      marker.title top.title
    end
    respond_to do |format|
      
      
      format.js 
    end
  end


	def top
    $location = {}
    $temp = params[:controller]
    topdestination = TopDestination.all
    castle = Castle.find_by_title("Castelul Bran")
    topdestination << castle
    castle = Castle.find_by_title("Castelul Peles")
    topdestination << castle
    @hash = Gmaps4rails.build_markers(topdestination) do |top, marker|
      marker.infowindow render_to_string(:partial => "/destinations/infowindow", :locals => { title: top.title, description: top.address})
      marker.lat top.latitude
      marker.lng top.longitude
      marker.title top.title
    end

    @tmp = 0
    @nr = 0

    all_table

		respond_to do |format|
      
      format.html
      format.js 
    end

  end	

  def comment
    @comment = Comment.new
    $er = params[:clas]
    respond_to do |format|
      format.js 
    
    end

  end


  def comment_show(array)

  end

  def create
    @comment = Comment.new(comment_params)
    verify = @comment.save
    $par = params.require(:comment).permit(:location_id)
   

    temp_location = TopDestination.find_by_id($par["location_id"])
    if !temp_location.nil?
      $location = information_com temp_location.title, TopDestination
    end

    temp_location = Castle.find_by_id($par["location_id"])
    if !temp_location.nil?
      $location = information_com temp_location.title, Castle
    end

    temp_location = City.find_by_id($par["location_id"])
    if !temp_location.nil?
      $location = information_com temp_location.title, City
    end
      # case par
      #   when !((temp_location = TopDestination.find_by_id(par)).nil?)
      #       @location = information_com temp_location.title, TopDestination
      #   when !((temp_location = Castle.find_by_id(par)).nil?)
      #       @location = information_com temp_location.title, Castle
      #   when !((temp_location = City.find_by_id(par)).nil?)
      #       @location = information_com temp_location.title, City
      #   else
      #       puts "adult"
      # end



    respond_to do |format|
      if verify

       format.js

      end
    end
   
  end
  

  def topdestination

  end

  def rate_loc
    location_id = params[:location_id]
    note = params[:note]
    r = RateLocation.where(:location_id => location_id, :user_id => current_user)
    if r.empty? 
    RateLocation.create(:note => note, :location_id => location_id, :user_id => current_user.id )
    else
     r[0].update(:note => note)
    end
   render :nothing => true
  end

  def rate_loc_value
    location_id = params[:location_id]

    r = RateLocation.where(:location_id => location_id)
    if !r.empty? 
      a = 0 
      n = 0
      r.each do |h|
        a += h.note
        n +=1 
      end
      respond_to do |format|
        format.js {render :json => {"note"=> a/n}}
      end
    end
  end


    private  

    def information_com(name, table)
      topdest = table.all
      top = topdest.find_by_title(name)
      com = Comment.where(:location_id => top.id)
      rate = RateLocation.where(:location_id => top.id)
      @h = Array.new
      # @h.compare_by_identity
      com.each do |t|
       
        # h["name"] = User.find_by_id(t.user_id).name
        # h["comm"] = t.com_text
         name =User.find_by_id(t.user_id).name
        # @h[name] = t.com_text
       
          @h << name 
          @h << t.com_text 
          @h << t.created_at
        
       
        
        puts @h

      end
      if rate.empty?
        @h << "note"
        @h << 0
      else
        nr = rate.size
        sum = 0
        rate.each do |t|
          sum += t.note
        end
        @h << "note"
        @h << sum/nr
      end
      @tmp = top.id
      @nr = @h.size
      @nr /=2
      @nr -=1
    return @h 

    end

    def all_table
       
    @sea = information_com("Marea Neagra", TopDestination)
    $sea_loc = @tmp
   
    @delta = information_com("Delta Dunarii", TopDestination)
    $delta_loc = @tmp
    # @sucevita = 

    @parliament = information_com("Casa Poporului", TopDestination)
    $parliament_loc = @tmp

    @sucevita = information_com("Manastirea Sucevita", TopDestination)
    $sucevita_loc = @tmp

    @moldovita = information_com("Manastirea Moldovita", TopDestination)
    $moldovita_loc = @tmp

    $arbore = information_com("Manastirea Arbore", TopDestination)
    $arbore_loc = @tmp

    @voronet = information_com("Manastirea Voronet",TopDestination)
    $voronet_loc = @tmp
    
    @bran = information_com("Castelul Bran", Castle)
    $bran_loc = @tmp

    @peles = information_com("Castelul Peles", Castle)
    $peles_loc = @tmp

    @corvinilor = information_com("Castelul Corvinilor",Castle)
    $corvinilor_loc = @tmp

    @balta = information_com("Cetatea de Balta",Castle)
    $balta_loc = @tmp    

    @fagaras = information_com("Cetatea Fagaras",Castle)
    $fagaras_loc = @tmp

    @prejmer = information_com("Cetatea Prejmer",Castle)
    $prejmer_loc = @tmp

    @rasnov = information_com("Cetatea Rasnov",Castle)
    $rasnov_loc = @tmp

    @brasov = information_com("Brasov", City)
    $brasov_loc = @tmp

    @bucuresti = information_com("Bucuresti", City)
    $bucuresti_loc = @tmp

    @cluj = information_com("Cluj", City)
    $cluj_loc = @tmp

    @constanta = information_com("Constanta", City)
    $constanta_loc = @tmp

    @iasi = information_com("Iasi", City)
    $iasi_loc = @tmp

    @timisoara = information_com("Timisoara", City)
    $timisoara_loc = @tmp
    end


    def comment_params
      params.require(:comment).permit(:com_text, :user_id, :location_id)
    end

end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/destinations/_comment.html.erb
	<% @loc_hash.each_slice(3) do |d| %>
					
		
			<% if d[0] != "note" %>

			<div class="text_comm">
				<section class="content row">
					<div class="col-lg-8">
						<p class="text_comm_p">
					 		<%= d[1] %>
						</p>
					</div>
					<div class="col-lg-4">

						<div >
							<p class="name_comm_p">
								User: <%= d[0] %>
							</p>
						</div>
						<div >
							<p class="date_comm_p">
								<%= d[2].strftime("at %I:%M%p, %m/%d/%Y")  %>
							</p>
						</div>
							
					</div>
				</section>
				
			</div>
		
			
		<% end %>
	<% end %>

			

app/views/destinations/_regions.html.erb
<h2> Regions </h2>

		<section class="topdestinations">
			<div id="destinationindex" class="row">
				<section class="scrollspy clearfix col col-lg-3 hidden-sm">

					<ul class="nav nav-list affix">
						<li><a href="#Banat_si_Crisana">Banat si Crisana</a></li>
						<li><a href="#Bucovina_si_Moldova">Bucovina si Moldova</a></li>
						<li><a href="#Dobrogea">Dobrogea</a></li>
						<li><a href="#Maramures">Maramures</a></li>
						<li><a href="#Transilvania">Transilvania</a></li>
						<li><a href="#Valahia">Valahia</a></li>
					</ul><!-- nav-list -->
				</section><!-- scrollspy -->
				<section class="destinationinfo col col-lg-9">
					<%= render "snippet_regions_banat_crisana"  %>
					<%= render "snippet_regions_bucovina_moldova"  %>
					<%= render "snippet_regions_dobrogea"  %>
					<%= render "snippet_regions_maramures"  %>
					<%= render "snippet_regions_transilvania"  %>
					<%= render "snippet_regions_valahia"  %>

				</section><!-- destinationinfo -->
			</div><!-- destinationindex -->
		</section><!-- topdestinations -->
		
		<script src="assets/myscrypt.js" type="text/javascript"></script>

app/views/destinations/_snippet_castles_castelul_corvinesti.html.erb
	<% $loc = $corvinilor_loc  %>
		<% if $location.empty? %>
			<% @loc_hash = @corvinilor %>
			
		<% else %>
			<% @loc_hash = $location %>
		<% end %>
		<% $clas = "comment_"+$loc.to_s %>


<article id="Castelul_Corvinestilor" class="media ">
		<section class="content row">
		<div class="col-lg-10">
			<h2>Corvinesti Castle in Hunedoara</h2>
		</div>
		<div class="col-lg-2">
			<%= render 'rate' %>
		</div>

	</section>
	
	<img src="" alt="">
	<div class="media-body">
		<p>The greatest Gothic-style castle in Romania, Corvinesti was built by the Anjou family on the site of a former Roman camp. The castle served as a fortress until the mid-14th century when it became the residence of Transylvania's ruler, Iancu de Hunedoara. Iancu upgraded the fortress transforming it into the most stunning castle in Transylvania.</p>
		<p>The beautifully preserved structure features a sumptuous Knights' Hall, an impressive drawbridge, high buttresses, inner courtyards, a chapel and some 50 rooms resplendent with medieval art. The courtyard features a 100 ft. well dug into stone.</p>
		<section class="modalphotos photogrid">
			<h3>Photos</h3>
			<img src="assets/Castles & Fortress/corvinesti/Castelul_Corvinesti_1_tn.jpg" alt="">
			<img src="assets/Castles & Fortress/corvinesti/Castelul_Corvinesti_2_tn.jpg" alt="">

		</section>
<h3>Comments</h3>
		<section class=<%= $clas %>>
				
			<%= render 'comment'  %>
			<% if current_user %>
			<%= link_to "Comment", comments_path(:clas => $clas,:loc => $loc), :remote => true, 
			 :class => "btn btn-primary button_text" %>
			<% end %>
		</section>
		
	</div><!-- media-body -->
</article>

app/views/destinations/_snippet_castles_cetatea_rasnov.html.erb
	<% $loc = $rasnov_loc  %>
		<% if $location.empty? %>
			<% @loc_hash = @rasnov %>
			
		<% else %>
			<% @loc_hash = $location %>
		<% end %>
		<% $clas = "comment_"+$loc.to_s %>


<article id="Cetatea_Rasnov" class="media">
	
	<section class="content row">
		<div class="col-lg-10">
			<h2>Rasnov Fortress</h2>
		</div>
		<div class="col-lg-2">
			<%= render 'rate' %>
		</div>

	</section>
	<img src="" alt="">
	<div class="media-body">
		<p>Rasnov Fortress (Rosenau in German), is located on a rocky hilltop in the Carpathian Mountains, 650 ft. above the town of Rasnov. First mentioned in an official document in 1331, the fortress was built by Teutonic Knights as protection against invading Tartars and was later enlarged by the local Saxon population.</p>
		<p>Recently, the old fortress has been restored to its former glory and today, you can visit the impressive remains. There is also a museum here, hidden behind the ancient walls, where you can find a skeleton buried beneath a glass floor, as well as some other interesting artifacts. 
</p>
		<section class="modalphotos photogrid">
			<h3>Photos</h3>
			<img src="assets/Castles & Fortress/rasnov/Cetatea_Rasnov_1_tn.jpg" alt="">
			<img src="assets/Castles & Fortress/rasnov/Cetatea_Rasnov_2_tn.jpg" alt="">
			<img src="assets/Castles & Fortress/rasnov/Cetatea_Rasnov_3_tn.jpg" alt="">

			



		</section>
<h3>Comments</h3>
		<section class=<%= $clas %>>
				
			<%= render 'comment'  %>
			<% if current_user %>
			<%= link_to "Comment", comments_path(:clas => $clas,:loc => $loc), :remote => true, 
			 :class => "btn btn-primary button_text" %>
			<% end %>
		</section>
		
	</div><!-- media-body -->
</article>

app/views/destinations/_snippet_castles_cetatea_valea_viilor.html.erb
<article id="Cetatea_Valea_Viilor" class="media">
	<h2>Cetatea Valea Viilor</h2>
	<img src="" alt="">
	<div class="media-body">
		<p>Cetatea si biserica fortificata din Valea Viilor face parte din multitudinea de ansambluri arhitectonice din Transilvania incluse in patrimoniul UNESCO.</p>
		<p>Biserica fortificata din Valea Viilor impresioneaza prin masivitatea si proportiile sale uriase, fiind totodata considerata una dintre cele mai marii edificii de cult religios din centrul Transilvaniei.
</p>
		<section class="modalphotos photogrid">
			<h3>Photos</h3>
			<img src="assets/Castles & Fortress/rasnov/Cetatea_Rasnov_1_tn.jpg" alt="">
			<img src="assets/Castles & Fortress/rasnov/Cetatea_Rasnov_2_tn.jpg" alt="">
			<img src="assets/Castles & Fortress/rasnov/Cetatea_Rasnov_3_tn.jpg" alt="">

			



		</section>


	
	</div><!-- media-body -->
</article>

app/views/destinations/_snippet_cities_iasi.html.erb
	<% $loc = $iasi_loc  %>
		<% if $location.empty? %>
			<% @loc_hash = @iasi %>
			
		<% else %>
			<% @loc_hash = $location %>
		<% end %>
		<% $clas = "comment_"+$loc.to_s %>



<article id="Iasi" class="media">
	
	<section class="content row">
		<div class="col-lg-10">
			<h2>Iasi</h2>
		</div>
		<div class="col-lg-2">
			<%= render 'rate' %>
		</div>

	</section>
	<img src="" alt="">
	<div class="media-body">
		
	<p>
		Iasi is the most important political, economic and cultural centre of the province of Moldavia as well as one of the oldest cities in Romania. 
	</p>
	<p>
		Deeply rooted in history, Iasi has been the main centre of Moldavian culture since 1408. The city prides itself with publishing the first Romanian newspaper and establishing the first Romanian university. Today, Iasi is home to five universities.
	</p>

		<section class="modalphotos photogrid">
			<h3>Photos</h3>
			<img src="assets/Cities & Towns/Iasi/Iasi_1_tn.jpg" alt="">
			<img src="assets/Cities & Towns/Iasi/Iasi_2_tn.jpg" alt="">
			<img src="assets/Cities & Towns/Iasi/Iasi_3_tn.jpg" alt="">
			<img src="assets/Cities & Towns/Iasi/Iasi_4_tn.jpg" alt="">
			<img src="assets/Cities & Towns/Iasi/Iasi_5_tn.jpg" alt="">
			
		</section>

<h3>Comments</h3>
		<section class=<%= $clas %>>
				
			<%= render 'comment'  %>
			<% if current_user %>
			<%= link_to "Comment", comments_path(:clas => $clas,:loc => $loc), :remote => true , 
			 :class => "btn btn-primary button_text"%>
			<% end %>
		</section>
		
	</div><!-- media-body -->
</article>

app/views/destinations/_snippet_destination_arbore.html.erb
	<% $loc = $arbore_loc  %>
		<% if $location.empty? %>
			<% @loc_hash = $arbore %>
			
		<% else %>
			<% @loc_hash = $location %>
			
		<% end %>
		<% $clas = "comment_"+$loc.to_s %>


<article id="Arbore" class="media">
	 <script src="assets/jquery.raty.js" type="text/javascript"></script>
	
	<section class="content row">
		<div class="col-lg-10">
			<h2> Arbore Monastery</h2>
		</div>
		<div class="col-lg-2">
			<%= render 'rate' %>
		</div>

	</section>
	
	<img src="" alt="">
	<div class="media-body">
			<p>Perhaps a tour of Bucovina’s Painted Monasteries should begin here. After all, the highlight of the small Arbore (Are' bo ray) church is a scene from Genesis, which adorns the western wall. 
			</p>
		<p> The only church in the region with no belfry towers, because it was not built by a prince, the monastery was founded in 1503 by Luca Arbore, the advisor of Stephen the Great (Stefan cel Mare). </p>
		
		
		<section class="modalphotos photogrid">
			<h3>Photos</h3>
					<img src="assets/Top Destination/Manastiri pictate/Manastirea_Arbore_1_tn.jpg" alt="">
					
	
		</section>
			<h3>Comments</h3>
		<section class=<%= $clas %> >
				
			<%= render 'comment'  %>
			<% if current_user %>
			<%= link_to "Comment", comments_path(:clas => $clas,:loc => $loc), :remote => true, 
			 :class => "btn btn-primary button_text"  %>
			<% end %>
	
		</section>

		
		
		
		</div>
	</article>

app/views/destinations/_snippet_destination_bran.html.erb
<article id="Bran_Castle" class="media">
	<h2>Bran Castle</h2>
	<img src="" alt="">
	<div class="media-body">
		<p>Castelul Bran se situează la mai puțin de 30 km de Brașov, pe șoseaua ce iese prin vechiul cartier Bartolomeu și care leagă Brașovul de Câmpulung. Castelul Bran este construit pe o stâncă, într-un punct cheie din punct de vedere strategic. El adăpostește în acest moment muzeul Bran, muzeu ce se întinde pe cele 4 etaje ale castelului.</p>
		<p>La muzeu sunt expuse colecții de ceramică, mobilier, arme și armuri, iar în curtea castelului se află un mic muzeu al satului, cu case tradiționale din regiunea culoarului Rucăr-Bran.
</p>
		<section class="modalphotos photogrid">
			<h3>Photos</h3>
			<img src="assets/Top Destination/Castelul Bran/Castelul_Bran_1_tn.jpg" alt="">
			<img src="assets/Top Destination/Castelul Bran/Castelul_Bran_2_tn.jpg" alt="">
			<img src="assets/Top Destination/Castelul Bran/Castelul_Bran_3_tn.jpg" alt="">
			<img src="assets/Top Destination/Castelul Bran/Castelul_Bran_4_tn.jpg" alt="">
		</section>



	</div><!-- media-body -->
</article>

app/views/destinations/_snippet_destination_peles.html.erb
<article id="Peles_Castle" class="media">
	<h2>Peles Castle</h2>
	<img src="" alt="">
	<div class="media-body">
		<p>Castelul Peleș din Sinaia, reședința de vară a regilor României, a fost construit la dorința regelui Carol I al României (1866 - 1914), după planurile arhitecților Johannes Schultz, Carol Benesch[1] și Karel Liman, și a fost decorat de celebrii decoratori J. D. Heymann din Hamburg, August Bembé din Mainz și Bernhard Ludwig din Viena.</p>
		<p>Castelul Peleș este unul dintre cele mai importante edificii de tip istoric din România, având caracter de unicat și este, prin valoarea sa istorică și artistică, unul din cele mai importante monumente de acest fel din Europa celei de a doua jumătăți a secolului al XIX-lea.
</p>
		<section class="modalphotos photogrid">
			<h3>Photos</h3>
			<img src="assets/Top Destination/Castelul Peles/Castelul_Peles_1_tn.jpg" alt="">
			<img src="assets/Top Destination/Castelul Peles/Castelul_Peles_2_tn.jpg" alt="">
			<img src="assets/Top Destination/Castelul Peles/Castelul_Peles_3_tn.jpg" alt="">
			<img src="assets/Top Destination/Castelul Peles/Castelul_Peles_4_tn.jpg" alt="">
		</section>


	</div><!-- media-body -->
</article>

app/views/destinations/_snippet_destination_sucevita.html.erb
			<% $loc = $sucevita_loc  %>
		<% if $location.empty? %>
			<% @loc_hash = @sucevita %>
			
		<% else %>
			<% @loc_hash = $location %>
		<% end %>
		<% $clas = "comment_"+$loc.to_s %>


<article id="Sucevita" class="media">
	
	<section class="content row">
		<div class="col-lg-10">
			<h2>Sucevita Monastery</h2>
		</div>
		<div class="col-lg-2">
			<%= render 'rate' %>
		</div>

	</section>
	<img src="" alt="">
	<div class="media-body">
	<p>High walls and heavily buttressed defensive towers surround the great monastic complex of Sucevita, giving it the appearance of a fortress. </p>
	<p> An elegant steeple resting on a star-shaped base tops the church. Massive eaves protect the outside frescoes, painted by local artists in 1602-1604.</p>
		
		
		<section class="modalphotos photogrid">
			<h3>Photos</h3>
			<img src="assets/Top Destination/Manastiri pictate/Manastirea_Sucevita_1_tn.jpg" alt="">
			<img src="assets/Top Destination/Manastiri pictate/Manastirea_Sucevita_2_tn.jpg" alt="">
		</section>
<h3>Comments</h3>
		<section class=<%= $clas %>>
				
			<%= render 'comment'  %>
			<% if current_user %>
			<%= link_to "Comment", comments_path(:clas => $clas,:loc => $loc), :remote => true, 
			 :class => "btn btn-primary button_text" %>
			<% end %>
		</section>
	
			</div>
	</article>
	

app/views/destinations/cities.js.erb
$('.main_container').empty();
$('.main_container').append("<%=j render 'cities_towns' %>");

app/views/destinations/create.js.erb
$('.<%= params[:clas] %>').empty()

	<% @loc_hash=$location %>		
$('.<%= params[:clas] %>').append("<%= j render 'comment' %>");

app/views/destinations/destinations_page.html.erb
		<div class = "container" id="destinations">
				<!-- <a>
					<img src="assets/Brasov_Square.jpg" alt="Brasov Square" style="max-width:100%">
				</a> -->
			<section class="content row">

				<div class="col-lg-12">
					<header class="clearfix">

							<section id="branding" class="brand">
							<a href="index.html"><img src="assets/romania-branding.png" alt="Logo for Romania" style="max-width:100%"></a>
						</section>
						<%= render "components/header" %>


					</header> <!--clearfix-->
				</div><!--column-->
			</section><!--content row-->

			<section class="container">
				<div class="content row">
					<nav class="col-lg-12 main_container">

					<h2>Destinations</h2>
							<p>Fortified churches and painted monasteries stand regally amid a pristine landscape. In the cities, former Saxon settlements such as Sibiu and Braşov ooze charm, while vibrant Bucharest is all energy.</p>



							<div class="content row my_content">
								<div class="col-lg-6 img_text left">
									<div class="fluid">

										<div class="top">
											<img src="">
										</div><!--top-->

										<img class="center_img" src="assets/Dochia_Cottage_tn.jpg" alt="Top Destinations" />
										<section class="inner">
											
											<%= link_to 'Top Destinations',  top_path, :remote => true, :class => "img_title"  %>
											
											<p>Although Romania is a relatively small country, it's land and countryside offers quite a few attractions never to be found somewhere else in the world. This is also the reason why UNESCO decided years ago to include them on it's List of World Cultural Heritage.</p>
										</section><!--inner-->
												<div class="clear foot">
													<img src="">
												</div>
										</div><!--fluid-->
								</div><!--col-lg-6 img_text-->

							<div class="col-lg-6 img_text">
								<div class="fluid">
											<div class="top">
												<img src="">
											</div>
											<img class="center_img" src="assets/University_Square_tn.jpg" alt="Cities & Towns" />
											<section class="inner">
												
												<%= link_to 'Cities & Towns',  cities_path, :remote => true, :class => "img_title"  %>
														<p>Some cities act as good starting points for exploring the Romania that few travelers get to see: out-of-the-way architectural treasures, pristine countryside, thick wilderness, or hidden castles.</p>
											</section>
											<div class="clear foot">
												<img src="">
											</div>
										</div>
							</div>
</div>
						<div class="content row my_content">
							<div class="col-lg-6 img_text left">
								<div class="fluid">
											<div class="top">
												<img src="">
											</div>
											<img class="center_img" src="assets/Bran_Castle_tn.jpg" alt="Castles & Fortresses" />
											<section class="inner">
										
												<%= link_to 'Castles & Fortresses',  castles_path, :remote => true, :class => "img_title"  %>
														<p>Romania's collection of castles and fortresses perhaps best illustrates the rich medieval heritage of the country. While castles built from the 14th to the 18th centuries are strong and austere fortresses built mainly for defense against invaders, those erected beginning in the late 1800s are imposing and luxurious.</p>
											</section>
											<div class="clear foot">
												<img src="">
											</div>
										</div>
							</div>

				

							</div><!--content row-->


					</nav><!--col-lg-12-->
				</div><!--row-->
			</section><!--container-->

			
			

		</div><!--container-->